### ISSUE TITLE
Racket support

### ISSUE THREAD

**Issue by Liffon** [odyssomay/sublime-lispindent#11]
It would be nice if this also supported [Racket](http://racket-lang.org/) files (`.rkt`). Since it's essentially a dialect of Scheme, it shouldn't be too hard to implement.

**Comment by odyssomay** [comment]
Definitely! :)

Do you think I should just add it as a scheme file, or should I do it separately?

**Comment by odyssomay** [comment]
I set it to use scheme indentation, for now.

I would like to do it separately, but I have a hard time finding the actual indenting code in drracket (which I'm assuming has the best racket indentation). Help with finding it would be appreciated. :)

**Comment by Liffon** [comment]
@odyssomay Wow, that was quick! :) I agree that doing it separately would be preferred for maximal niceness, but Scheme indentation definitely works as a start.

There is a list of keywords and how they should behave under `Preferences -> Editing` in Dr Racket, maybe that's a place to start? I'd like to help with writing the rules but I'm not too familiar with the Sublime Text indentation syntax ...

**Comment by odyssomay** [comment]
So the indation is either:

"Function" (argument) indent (the arguments are aligned)

``` scheme
(call arg1
      arg2
      arg3)
```

"two-space" indent, indents two spaces from last open parenthesis

``` scheme
(let ((a 3))
  a
  4)
```

The function indent is the default, the two-space is the exception for a select few functions. Basically what I need is a list of the functions that should use two-space indent. If you want to help, you can write - in a comment - a list of the functions that should use two-space indent (in whatever format you prefer).

Please tell me if you intend to write this list or not. If you don't quite understand or don't want to - that's fine. In that case I'll try to do it myself.

**Comment by odyssomay** [comment]
I've started looking at this.

**Comment by Liffon** [comment]
I've started looking at this too. I think I will have a complete list soon.

**Comment by odyssomay** [comment]
Oops! Alright. I think I will complete my list anyway, then compare them. Because it was much more complicated than I originally thought. drracket doesn't make the distinction as clear between the different indents, and on top of that, some functions seem to be using their own custom indenting.

**Comment by Liffon** [comment]
From playing around a bit with Dr Racket, this is what I've got:

It seems like Dr Racket in fact uses three versions of the two-space indentation rule: `begin`-like, `define`-like and `lambda`-like. From what I can see, they behave like this:

##### begin-like:

 If there is a linebreak right after the keyword, indent two spaces, otherwise align arguments.

``` racket
(begin
  one
  two
  three)

(begin one
       two
       three)
```

According to the default settings in Dr Racket, the keywords that use this rule are `begin`, `case-lambda`, `case-lambda:`, `compund-unit`, `compund-unit/sig`, `cond`, `delay`, `inherit`, `match-lambda`, `match-lambda*`, `override`, `pcase-lambda:`, `private`, `public`, `sequence` and `unit`.

##### define-like:

Pretty much like the default two-space rule -- always indent two spaces from last open parenthesis.

``` racket
(define one
  two
  three)

(define one two
  three)

(define
  one
  two
  three)
```

Keywords: `define`, `define-predicate`, `define-struct/exec:`, `define-struct:`, `define-type`, `define-typed-struct`, `define:`, `local`, `match-define`, `pdefine:`, `struct` and `struct:`

##### lambda-like:

Indent the first argument four spaces if and only if it has its own row and the rest two spaces.

``` racket
(lambda one
  two ;; just two spaces
  three)

(lambda
    one ;; first argument on its own line, so indent four spaces
  two
  three)
```

Keywords (this one has a lot of them): `call-with-input-file`, `call-with-input-file*`, `call-with-output-file`, `case`, `cases`, `catch`, `class`, `class*`, `class*/names`, `class-asi`, `class100`, `class100*`, `class100*/names`, `class100-asi`, `class100-asi*`, `define-record`, `define-some`, `do`, `do:`, `fluid-let`, `fluid-let-syntax`, `for`, `for*`, `for*/and`, `for*/and:`, `for*/first`, `for*/first:`, `for*/flvector`, `for*/flvector:`, `for*/fold`, `for*/fold:`, `for*/hash`, `for*/hash:`, `for*/hasheq`, `for*/hasheq:`, `for*/hasheqv`, `for*/hasheqv:`, `for*/last`, `for*/last:`, `for*/list`, `for*/list:`, `for*/lists`, `for*/lists:`, `for*/or`, `for*/or:`, `for*/product`, `for*/product:`, `for*/sum`, `for*/sum:`, `for*/vector`, `for*/vector:`, `for*:`, `for-all`, `for/and`, `for/and:`, `for/first`, `for/first:`, `for/flvector`, `for/flvector:`, `for/fold`, `for/fold:`, `for/hash`, `for/hash:`, `for/hasheq`, `for/hasheq:`, `for/hasheqv`, `for/hasheqv:`, `for/last`, `for/last:`, `for/list`, `for/list:`, `for/lists`, `for/lists:`, `for/or`, `for/or:`, `for/product`, `for/product:`, `for/sum`, `for/sum:`, `for/vector`, `for/vector:`, `for:`, `instantiate`, `interface`, `kernel-syntax-case`, `lambda`, `lambda/kw`, `lambda:`, `let`, `let*`, `let*-values`, `let*-values:`, `let*:`, `let-enumerate`, `let-macro`, `let-signature`, `let-struct`, `let-syntax`, `let-values`, `let-values:`, `let/cc`, `let/cc:`, `let/ec`, `let/ec:`, `let:`, `letcc`, `letrec`, `letrec-syntax`, `letrec-syntaxes+values`, `letrec-values`, `letrec-values:`, `letrec:`, `make-object`, `match`, `match*`, `match-let`, `match-let*`, `match-letrec`, `mixin`, `module`, `module*`, `module+`, `opt-lambda`, `opt-lambda:`, `parameterize`, `plambda:`, `popt-lambda:`, `quasisyntax/loc`, `rec`, `recur`, `send*`, `shared`, `splicing-let`, `splicing-let-syntax`, `splicing-let-syntaxes`, `splicing-let-values`, `splicing-letrec`, `splicing-letrec-syntax`, `splicing-letrec-syntaxes`, `splicing-letrec-syntaxes+values`, `splicing-letrec-values`, `splicing-local`, `splicing-syntax-parameterize`, `super-instantiate`, `syntax-case`, `syntax-case*`, `syntax-id-rules`, `syntax-rules`, `syntax/loc`, `type-case`, `unit/lang`, `unit/sig`, `unless`, `when`, `with-continuation-mark`, `with-handlers`, `with-input-from-file`, `with-input-from-port`, `with-method`, `with-output-to-file`, `with-output-to-port`, `with-syntax`, `λ`, `λ:`

**Comment by odyssomay** [comment]
Note that _lambda-like_ is always using two-space indent. The four spaces thing is not really possible with the current implementation. I hope this is acceptable. :)

**Comment by Liffon** [comment]
Of course!
