### ISSUE TITLE
Clojure: multi line doc comment breaks indentation

### ISSUE THREAD

**Issue by hlship** [odyssomay/sublime-lispindent#18]
With no doc comment, or a single-line doc comment, indentation is correct:

```
(defn- transform-values 
  "Transforms a map by passing each value through a provided function."
  [m f]
  (into {} (map (fn [[k v]] [k (f v)]))))
```

If I then make the docstring multi line and reindent the entire function:

```
defn- transform-values 
  "Transforms a map by passing each value through a provided function.

  This is now a multi-line comment."
[m f]
(into {} (map (fn [[k v]] [k (f v)])))
```

The function body should be indented one level (two spaces, for me).

**Comment by hlship** [comment]
Version: 2013.06.28.19.44.00 on Mac OS X, Sublime Text 2

**Comment by odyssomay** [comment]
Thanks for reporting! :+1: 

Reopen if it still doesn't work. Note that it takes up to 30 minutes for the package to update.

**Comment by hlship** [comment]
Thanks for the fix, worked fine!
