### ISSUE TITLE
Reindent all expressions

### ISSUE THREAD

**Issue by wiiittttt** [odyssomay/sublime-lispindent#19]
Currently lispindent (ctrl+i) will only indent the first expression on a line. Would it be possible to parse the entire line/selection to re-indent everything?

From:

``` clojure
(defn foo [& args] (println "Indent me!") (-> (slurp file) (clojure.string/split-lines)))
```

To:

``` clojure
(defn foo
  [& args]
  (println "Indent me!")
  (-> (slurp file)
      (clojure.string/split-lines)))
```

**Comment by odyssomay** [comment]
It does indent the whole line, it also indents the selection. Lispindent never inserts space though. That's not what it's supposed to do.

What lispindent does:
1. Inserts the correct amount of spaces (the correct indenting) when you press enter.
2. Fixes the indenting at the beginning of each line in the selection (or current line).

**Comment by wiiittttt** [comment]
Sorry, I was more asking if it would be possible to create a shortcut to essentially "press enter" before every expression in a long line of code. So if I had a huge one liner that I copied from somewhere else, it would quickly reindent everything instead of having to go to each expression and press enter manually.

**Comment by odyssomay** [comment]
I'm sorry, but no. There is too much missing in lispindent. To begin with, lispindent doesn't even know what an expression is. Also, I don't think it's really that useful - most code already have newlines or is short enough to manually insert them. I hope you're okay with this. :(

**Comment by wiiittttt** [comment]
No problem. Thanks.
