### ISSUE TITLE
lispindent inserts trailing whitespace

### ISSUE THREAD

**Issue by radix** [odyssomay/sublime-lispindent#21]
This is on ST3.

If I select a region like this:

```
(deftest

(is (= "foo" "foo") "foo equals foo")

(is (= "bar" "bar") "bar equals bar"))
```

lispindent will put whitespace (two space characters) on the previously empty lines. It'd be nice to avoid this.

**Comment by odyssomay** [comment]
The algorithm can use empty lines to determine indentation. This change would disrupt that and make calculating indentation much slower in some cases. So right now I don't think it's a good idea. Sorry!

**Comment by mrcslws** [comment]
Hmm, I just came here to report this same issue.

**Comment by radix** [comment]
Not that I know anything about how to implement these things, but couldn't the indentation-determination algorithm continue searching backwards if there's an empty line?

**Comment by odyssomay** [comment]
I guess that could work. It would hurt performance though. It would also break behaviour in some rare cases.
