### ISSUE TITLE
defmacro in clojure does not get indented the right way

### ISSUE THREAD

**Issue by GorgeRonde** [odyssomay/sublime-lispindent#3]
defmacro is indented as 'normal' functions :
say I have

``` clojure
(defmacro macro-name [args]|)
```

then press enter to write the body, I get

``` clojure
(defmacro macro-name [args]
                     |)
```

instead of

``` clojure
(defmacro macro-name [args]
   |)
```

I fixed this by adding defmacro to clojure regex field in the config map of lispindent.
It was just missing I guess.

**Comment by odyssomay** [comment]
Thanks for reporting.

This is fixed in the latest version - ab386dd .
