### ISSUE TITLE
defn- is not indented properly

### ISSUE THREAD

**Issue by madnl** [odyssomay/sublime-lispindent#6]
Indentation for private function definitions doesn't work as it should.

Current behavior:

```
(defn- private-fun [x]
       (+ x 1))
```

Expected behavior:

```
(defn- private-fun [x]
  (+ x 1))
```

**Comment by odyssomay** [comment]
Thanks for reporting! :)

Since 3f99bb4 I have made all functions/macros that starts with `def` use 'two space indent' (your bottom one). This will also make indentation better for libraries such as leiningen and noir.
